# -----------------------------------------------------------------------------
# Build workflow for portable apps
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.10.0
# -----------------------------------------------------------------------------
name: build-linux

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  build-linux:
    if: endsWith(github.repository, 'Portable')
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build script via docker
      shell: bash
      run: |2+ 
        docker run \
          --rm \
          --tty \
          --env USER_UID=$(id -u) \
          --env USER_GID=$(id -g) \
          --mount type=bind,src=$(cd ../; pwd),target=/PortableApps \
          --workdir=/PortableApps/$(realpath --relative-to=../  .) \
          uroesch/pa-wine:latest \
          /usr/bin/pwsh -ExecutionPolicy ByPass Other/Update/Update.ps1 -InfraDir /pa-build
      timeout-minutes: 10

    - name: Collect logs on failure
      if: failure()
      shell: bash
      run: |
        mkdir ../artifacts
        cp ../PortableApps.com*/Data/*Log.txt ../artifacts

    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: logs.zip
        path: ../artifacts
