# This is a test workflow
name: test-build-ci

on:
  push:
    branches: [ test-build ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: run update
      run: Other/Update/Update.ps1
