# -----------------------------------------------------------------------------
# VirusTotal scan for portable apps
# Author: Urs Roesch https://github.com/uroesch copied from action example
# Version: 0.1.0 
# -----------------------------------------------------------------------------
name: virustotal-scan

on:
  release:
    types: 
      - published

jobs:
  virustotal-scan:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        id: vt
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_release_body: true
          files: |
            *.exe
